### ISSUE TITLE
Tried to replicate without success

### ISSUE THREAD

**Issue by juangea** [bublint/ue5-llama-lora#1]
Hello.

I tried to replicate the LORA training but had no success, I'm not sure if it's because the model, I tried several in the end I tried this llama one:

https://huggingface.co/decapoda-research/llama-7b-hf

But I'm not sure if it'0s the correct one, I'm very interested in this, it could be very helpful to have a local assistant to some specific documentation in some specific software, pretty cool, I hope you can help me out.

Is that the correct model to use? if it's not, where can I download the correct model?

Thanks!

**Comment by juangea** [comment]
Ok, it seems the problem was my txt file, it had some non-ascii characters, when I solved this the training seems to start without trouble, will see the results, thanks for the guide for this!

If there is a better model for this please tell me :)

**Comment by Alpha-Leader** [comment]
What issues were you running into? Did it keep telling you to use 8bit mode?

**Comment by juangea** [comment]
I had to use 8-Bit mode, but the main problem was that my txt was incorrect, with some non-ascii characters, after I cleaned it up it worked, although the train was completely useless, I have to check why.

I will try to use the Python here to get all the documentation and see if they helps, because so far my try was useless.

Any advice on train settings is welcome :)
