### ISSUE TITLE
what is the machine that you used 

### ISSUE THREAD

**Issue by vigneshmj1997** [bublint/ue5-llama-lora#8]
Can I know the ram and other configuration of the machine that you used

**Comment by bublint** [comment]
Sure! Here you go:
- CPU: i7-11700K - ID-COOLING AURAFLOW X 240 Snow AIO
- RAM: Corsair Vengeance RGB PRO SL 4x16GB DDR4 @ 3600 MHz
- GPU: EVGA 3090Ti FTW3 - stock cooler
- MOBO: Asus Prime Z590-P WiFi
- Case: Lian Li PC-O11 white
- Model was loaded from SATA SSD
